# **Stochastic Gradient Descent Regressor**

In [98]:
from sklearn.datasets import load_diabetes
import numpy as np 
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
import time

In [99]:
X,y = load_diabetes(return_X_y=True)

In [100]:
print(X.shape)
print(y.shape)

(442, 10)
(442,)


In [101]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=3)

In [102]:
reg = LinearRegression()
reg.fit(X_train, y_train)

LinearRegression()

In [103]:
print(reg.coef_)
print(reg.intercept_)

[  -1.13744712 -212.8867836   540.45536994  345.20621542 -938.23814645
  516.62060367  172.85885498  267.87535242  732.63230159   70.07849485]
153.13441535285003


In [104]:
y_pred = reg.predict(X_test)
r2_score(y_test, y_pred)

0.4161792211496942

In [105]:
from sklearn.linear_model import SGDRegressor

In [106]:
model = SGDRegressor(max_iter=100, learning_rate='constant', eta0=0.1)
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
r2_score(y_test,y_pred)

0.3688923140119085

In [107]:
model.coef_

array([   3.41270969, -170.28332991,  495.80358778,  310.44008433,
        -79.99474462, -122.24696877, -221.04777878,  138.94977294,
        381.5432284 ,  120.41499874])

In [108]:
model.intercept_

array([164.86563089])

In [109]:
class OurSGD:
    def __init__(self, learning_rate=0.01, epochs=100):
        self.coef_ = None
        self.intercept_ = None
        self.lr = learning_rate
        self.epochs = epochs

    def fit(self, X_train, y_train):
        # init coefs
        self.intercept_ = 0
        self.coef_ = np.ones(X_train.shape[1])

        for i in range(self.epochs):
            for j in range(X_train.shape[0]):
                idx = np.random.randint(0, X_train.shape[0])

                y_hat = np.dot(X_train[idx], self.coef_) + self.intercept_

                intercept_der = -2 * (y_train[idx] - y_hat)
                self.intercept_ = self.intercept_ - (self.lr * intercept_der)

                coef_der = -2 * np.dot((y_train[idx] - y_hat), X_train[idx])
                self.coef_ = self.coef_ - (self.lr * coef_der)

    def predict(self, X_test):
        return np.dot(X_test, self.coef_) + self.intercept_            

In [110]:
our = OurSGD(learning_rate=0.1, epochs=55)

In [111]:
start = time.time()
our.fit(X_train, y_train)
print('time taken :', time.time() - start)

time taken : 1.3711895942687988


In [112]:
y_pred = our.predict(X_test)
r2_score(y_test, y_pred)

0.4229749605174058

In [113]:
our.coef_

array([  11.56421665, -204.21637844,  540.9935301 ,  351.28591555,
       -119.50960674, -118.44410065, -170.16369179,  166.08075379,
        437.77278419,   53.84270772])

In [114]:
our.intercept_

153.2005091781442